### ISSUE TITLE
English word lists

### ISSUE THREAD

**Issue by muranava** [fildpauz/vocab-lists#1]
Hi 
Many hanks for this resource of multilingual lists!
If you are looking for a continuously updated list of English that includes general lists, academic lists, discipline lists and formulaic lists please have a look here - https://eflnotes.wordpress.com/english-wordlists/
Regards
Mura

**Comment by fildpauz** [comment]
Mura,

Thank you very much for the comments.  I'll add a link to your list page.

Sincerely,
Ralph
